---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demonstration
spec:
  storageClassName: "manual"
  capacity:
    storage: 64Gi
  accessModes:
    - ReadOnlyMany
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/YOUR_PROJECT_HERE/zones/us-central1-c/disks/demonstration
    fsType: ext4
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demonstration
spec:
  storageClassName: manual
  volumeName: demonstration
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: demonstration-1
spec:
  containers:
  - name: demonstration
    image: nginx
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: demonstration
---
apiVersion: v1
kind: Pod
metadata:
  name: demonstration-2
spec:
  containers:
  - name: demonstration
    image: nginx
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: demonstration